new appmotion-gateway-1.1rc
ITISFoundation/osparc-ops-environments pull request #597
Opened 2024-03-06 13:44 UTC by pcrespov

## What do these changes do?

## Related issue/s

## Related PR/s

## Checklist

- [ ] I tested and it works

2024-03-06 13:53 UTC, mrnicegyu11 approved these changes

2024-03-06 14:21 UTC, matusdrobuliak66 approved these changes

2024-03-06 21:21 UTC, matusdrobuliak66 requested changes
We need to build a new image with latest changes

2024-03-07 10:57 UTC, pcrespov commented
> We need to build a new image with latest changes

Updated to `v1.2rc-2024-03-07-10-51`

2024-03-07 10:57 UTC, matusdrobuliak66 approved these changes

2024-03-09 10:53 UTC, matusdrobuliak66 approved these changes

2024-03-09 10:54 UTC, merged